-> Switch to 3.7.0 image

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -1,6 +1,6 @@
 version: 2.1
 commands:
-  setup_vars:
+  deployment_setup:
     steps:
       - run:
           name: "Set the Tier"
@@ -10,27 +10,57 @@ commands:
               TIER=$(awk -F- '{print toupper($3)}' \<<< ${CIRCLE_BRANCH})
             fi
             echo "export TIER=${TIER}" >> $BASH_ENV
-            echo "Tier was identified as ${TIER}"
+            echo "Tier was identified as ${TIER} for branch ${CIRCLE_BRANCH}"
       - run:
           name: "Assign Project-level vars"
           command: |
+            KEY=${DEPLOYMENT_KEY_ISB_CGC}
+            CLIENT_EMAIL=${DEPLOYMENT_CLIENT_EMAIL_ISB_CGC}
+            PROJECT_ID=${DEPLOYMENT_PROJECT_ID_ISB_CGC}
             if [[ ${TIER} == "PROD" ]] || [[ ${TIER} == "DEV" ]]; then
-              echo "Found isb-cgc"
-              echo "export DEPLOYMENT_KEY=\"${DEPLOYMENT_KEY_ISB_CGC}\"" >> $BASH_ENV
-              echo "export DEPLOYMENT_CLIENT_EMAIL=${DEPLOYMENT_CLIENT_EMAIL_ISB_CGC}" >> $BASH_ENV
-              echo "export DEPLOYMENT_PROJECT_ID=${DEV_PROJECT_ID}" >> $BASH_ENV
+              echo "Using default project ${PROJECT_ID} and related deployment SA."
             elif [[ ${TIER} == "UAT" ]]; then
-              echo "Found isb-cgc-uat"
-              echo "export DEPLOYMENT_KEY=${DEPLOYMENT_KEY_ISB_CGC_UAT}" >> $BASH_ENV
-              echo "export DEPLOYMENT_CLIENT_EMAIL=${DEPLOYMENT_CLIENT_EMAIL_ISB_CGC_UAT}" >> $BASH_ENV
-              echo "export DEPLOYMENT_PROJECT_ID=${DEPLOYMENT_PROJECT_ID_ISB_CGC_UAT}" >> $BASH_ENV
+              KEY=${DEPLOYMENT_KEY_ISB_CGC_UAT}
+              CLIENT_EMAIL=${DEPLOYMENT_CLIENT_EMAIL_ISB_CGC_UAT}
+              PROJECT_ID=${DEPLOYMENT_PROJECT_ID_ISB_CGC_UAT}
             elif [[ ${TIER} == "TEST" ]]; then
-              echo "Found isb-cgc-test"
-              echo "export DEPLOYMENT_KEY=${DEPLOYMENT_KEY_ISB_CGC_TEST}" >> $BASH_ENV
-              echo "export DEPLOYMENT_CLIENT_EMAIL=${DEPLOYMENT_CLIENT_EMAIL_ISB_CGC_TEST}" >> $BASH_ENV
-              echo "export DEPLOYMENT_PROJECT_ID=${DEPLOYMENT_PROJECT_ID_ISB_CGC_TEST}" >> $BASH_ENV
+              KEY=${DEPLOYMENT_KEY_ISB_CGC_TEST}
+              CLIENT_EMAIL=${DEPLOYMENT_CLIENT_EMAIL_ISB_CGC_TEST}
+              PROJECT_ID=${DEPLOYMENT_PROJECT_ID_ISB_CGC_TEST}
+            else
+              echo "[ERROR] - Unrecognized tier: ${TIER} - exitng."
+              exit 1
+            fi
+
+            echo "export DEPLOYMENT_KEY=\"${KEY}\"" >> $BASH_ENV
+            echo "export DEPLOYMENT_CLIENT_EMAIL=${CLIENT_EMAIL}" >> $BASH_ENV
+            echo "export DEPLOYMENT_PROJECT_ID=${PROJECT_ID}" >> $BASH_ENV
+
+      - run:
+          name: "Set tier-specific configuration file"
+          command: |
+            CONFIG_FILE=${DEPLOYMENT_CONFIG_FILE_DEV}
+            if [[ ${TIER} == "PROD" ]]; then
+              echo "Deployment configuration set for production."
+              CONFIG_FILE=${DEPLOYMENT_CONFIG_FILE_PROD}
+            elif [[ ${TIER} == "UAT" ]]; then
+              echo "Deployment configuration set for production."
+              CONFIG_FILE=${DEPLOYMENT_CONFIG_FILE_UAT}
+            elif [[ ${TIER} == "TEST" ]]; then
+              echo "Deployment configuration set for production."
+              CONFIG_FILE=${DEPLOYMENT_CONFIG_FILE_TEST}
+            elif [[ ${TIER} == "DEV" ]]; then
+              echo "Deployment configuration set for production."
             else
               echo "[ERROR] - Unrecognized tier: ${TIER}"
+              CONFIG_FILE=
+            fi
+
+            if [[ -n $CONFIG_FILE ]]; then
+              echo "export DEPLOYMENT_CONFIG_FILE=${CONFIG_FILE}" >> $BASH_ENV
+            else
+              echo "[ERROR] Couldn't assign deployment configuration file - exiting."
+              exit 1
             fi
 
 jobs:
@@ -39,7 +69,7 @@ jobs:
       TZ: "/usr/share/zoneinfo/America/Los_Angeles"
     working_directory: ~/ISB-CGC-Webapp
     docker:
-      - image: circleci/python:3.5.6
+      - image: circleci/python:3.7.0
       - image: circleci/mysql:5.7
         environment:
           MYSQL_ROOT_HOST: "%"
@@ -66,7 +96,7 @@ jobs:
           key: isb-cgc-webapp-lib-{{ checksum "requirements.txt" }}
           paths:
             - ./lib
-      - setup_vars
+      - deployment_setup
       - run:
           name: Auth, Staging, and Database testing
           command: |
